Web App/Controllers/AccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Web_App.Data.Account;

namespace Web_App.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AccountController : ControllerBase
    {
        private readonly SignInManager<User> signInManager;

        public AccountController(SignInManager<User> signInManager)
        {
            this.signInManager = signInManager;
        }

        public async Task<IActionResult> ExternalLoginCallback()
        {
            var loginInfo = await signInManager.GetExternalLoginInfoAsync();
            var emailClaim = loginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email);
            var userClaim = loginInfo.Principal.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name);

            if (emailClaim != null && userClaim != null)
            {
                var user = new User { UserName = emailClaim.Value, Email = userClaim.Value };
                await signInManager.SignInAsync(user, isPersistent: false);
            }

            return RedirectToPage("/Index");
        }
    }
}

Web App/Pages/Account/AuthenticatorWithMFA.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QRCoder;
using Web_App.Data.Account;

namespace Web_App.Pages.Account
{
    [Authorize]
    public class AuthenticatorWithMFAModel : PageModel
    {
        private readonly UserManager<User> userManager;

        [BindProperty]
        public SetupMFAViewModel MFAViewModel { get; set; } = new();
        public bool SetupSuccess { get; set; }

        public AuthenticatorWithMFAModel(UserManager<User> userManager)
        {
            this.userManager = userManager;
        }
        public async Task OnGetAsync()
        {
            var user = await userManager.GetUserAsync(base.User);
            await userManager.ResetAuthenticatorKeyAsync(user);
            this.MFAViewModel.Key = await userManager.GetAuthenticatorKeyAsync(user);
            this.MFAViewModel.QrCodeBytes = GenerateQrCodeBytes("Identity", this.MFAViewModel.Key, user.Email);
        }

        public async Task OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.GetUserAsync(base.User);
                if (await userManager.VerifyTwoFactorTokenAsync(user, userManager.Options.Tokens.AuthenticatorTokenProvider, this.MFAViewModel.SecurityCode))
                {
                    await userManager.SetTwoFactorEnabledAsync(user, true);
                    this.SetupSuccess = true;
                }
                else
                {
                    ModelState.AddModelError("AuthenticatorSetup", "Error with Authenticator set up");
                }
            }
        }

        private Byte[] GenerateQrCodeBytes(string Provider, string Key, string UserEmail)
        {
            var qrCodeGenerator = new QRCodeGenerator();
            //qrCodeGenerator.CreateQrCode($"otpauth://totp/{provider}:{UserEmail}?secret={Key}&issuer={Provider}&digits=6")
            var qrData = qrCodeGenerator.CreateQrCode($"otpauth://totp/{Provider}:{UserEmail}?secret={Key}&issuer={Provider}", QRCodeGenerator.ECCLevel.Q);
            var qrPng = new PngByteQRCode(qrData);
            return qrPng.GetGraphic(20);
        }
    }

    public class SetupMFAViewModel
    {
        public string Key { get; set; }
        public string SecurityCode { get; set; }
        public Byte[] QrCodeBytes { get; set; }
    }
}

Web App/Pages/Account/ConfirmEmail.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web_App.Data.Account;

namespace Web_App.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<User> userManager;
        [BindProperty]
        public string Message { get; set; }
        public ConfirmEmailModel(UserManager<User> userManager)
        {
            this.userManager = userManager;
        }
        public async Task<IActionResult> OnGetAsync(string userId, string token)
        {
            var user = await this.userManager.FindByIdAsync(userId);

            if (user is not null)
            {
                var result = await this.userManager.ConfirmEmailAsync(user, token);
                if (result.Succeeded)
                {
                    this.Message = "Email address successfully confirmed, you can now login";
                    return Page();
                }
            }

            this.Message = "Failed to validate email";
            return Page();
        }
    }
}

Web App/Pages/Account/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Web_App.Data.Account;

namespace Web_App.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<User> signInManager;
        private readonly UserManager<User> userManager;

        public LoginModel(SignInManager<User> signInManager, UserManager<User> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        [BindProperty]
        public CredentialViewModel CredentialViewModel { get; set; }

        [BindProperty]
        public IEnumerable<AuthenticationScheme> ExternalLoginProviders { get; set; }
        public async Task OnGetAsync()
        {
            this.ExternalLoginProviders = await signInManager.GetExternalAuthenticationSchemesAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var result = await signInManager.PasswordSignInAsync(this.CredentialViewModel.Email, this.CredentialViewModel.Password, this.CredentialViewModel.RememberMe, false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.RequiresTwoFactor)
                {
                    var user = await userManager.FindByEmailAsync(this.CredentialViewModel.Email);
                    if (string.IsNullOrWhiteSpace(await userManager.GetAuthenticatorKeyAsync(user))) 
                    {
                        return RedirectToPage("/Account/LoginTwoFactor", new
                        {
                            Email = this.CredentialViewModel.Email,
                            RememberMe = this.CredentialViewModel.RememberMe
                        });
                    }
                    else
                    {
                        return RedirectToPage("/Account/LoginTwoFactorAuthenticator", new
                        {
                            RememberMe = this.CredentialViewModel.RememberMe
                        });
                    }
                }
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Login", "You are locked out");
                }
                else
                {
                    ModelState.AddModelError("Login", "Failed to login");
                }
                return Page();
            }
        }

        public IActionResult OnPostLoginExternally(string provider)
        {
            var properties = signInManager.ConfigureExternalAuthenticationProperties(provider, null);
            properties.RedirectUri = Url.Action("ExternalLoginCallback", "Account");

            return Challenge(properties, provider);
        }

    }

    public class CredentialViewModel
    {
        [Required]
        public string Email { get; set; }
        [Required]
        [DataType(dataType: DataType.Password)]
        public string Password { get; set; }
        [Display(Name = "Remember Me")]
        public bool RememberMe { get; set; }

    }
}

Web App/Pages/Account/LoginTwoFactor.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Web_App.Data.Account;
using Web_App.Services;

namespace Web_App.Pages.Account
{
    public class LoginTwoFactorModel : PageModel
    {
        private readonly UserManager<User> userManager;
        private readonly IEmailService _emailService;
        private readonly SignInManager<User> signInManager;

        [BindProperty]
        public EmailMFA EmailMFA { get; set; } = new();

        public LoginTwoFactorModel(UserManager<User> userManager, IEmailService emailService, SignInManager<User> signInManager)
        {
            this.userManager = userManager;
            this._emailService = emailService;
            this.signInManager = signInManager;
        }

        public async Task OnGetAsync(string email, bool rememberMe)
        {
            var user = await userManager.FindByEmailAsync(email);

            this.EmailMFA.SecurityCode = string.Empty;
            this.EmailMFA.RememberMe = rememberMe;

            var securityCode = await userManager.GenerateTwoFactorTokenAsync(user, "Email");

            await _emailService.SendConfirmationAsync(email, "Token", $"Use this as the token: {securityCode}");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await signInManager.TwoFactorSignInAsync("Email",
                this.EmailMFA.SecurityCode,
                this.EmailMFA.RememberMe,
                false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Login2FA", "You are locked out.");
                }
                else
                {
                    ModelState.AddModelError("Login2FA", "Failed to login.");
                }

                return Page();
            }
        }
    }

    public class EmailMFA
    {
        [Required]
        [Display(Name = "Security Code")]
        public string SecurityCode { get; set; }
        public bool RememberMe { get; set; }
    }
}

Web App/Pages/Account/LoginTwoFactorAuthenticator.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Web_App.Data.Account;
using Web_App.Services;

namespace Web_App.Pages.Account
{
    public class LoginTwoFactorAuthenticatorModel : PageModel
    {
        private readonly UserManager<User> userManager;        
        private readonly SignInManager<User> signInManager;

        [BindProperty]
        public AuthenticatorMFA AuthenticatorMFA { get; set; } = new();

        public LoginTwoFactorAuthenticatorModel(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public async Task OnGetAsync(bool rememberMe)
        {
            this.AuthenticatorMFA.SecurityCode = string.Empty;
            this.AuthenticatorMFA.RememberMe = rememberMe;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var result = await signInManager.TwoFactorAuthenticatorSignInAsync(this.AuthenticatorMFA.SecurityCode,
                this.AuthenticatorMFA.RememberMe,
                false);

            if (result.Succeeded)
            {
                return RedirectToPage("/Index");
            }
            else
            {
                if (result.IsLockedOut)
                {
                    ModelState.AddModelError("Authenticator2FA", "You are locked out.");
                }
                else
                {
                    ModelState.AddModelError("Authenticator2FA", "Failed to login.");
                }

                return Page();
            }
        }
    }

    public class AuthenticatorMFA
    {
        [Required]
        [Display(Name = "Security Code")]
        public string SecurityCode { get; set; }
        public bool RememberMe { get; set; }
    }
}

Web App/Pages/Account/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web_App.Data.Account;

namespace Web_App.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<User> _signInManager;

        public LogoutModel(SignInManager<User> signInManager) 
        {
            _signInManager = signInManager;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToPage("/Account/Login");
        }
    }
}

Web App/Pages/Account/Register.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Net;
using System.Net.Mail;
using Web_App.Data;
using Web_App.Data.Account;
using Web_App.Services;

namespace Web_App.Pages.Account
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<User> userManager;
        private readonly IEmailService _emailService;

        public RegisterModel(UserManager<User> userManager, IEmailService emailService)
        {
            this.userManager = userManager;
            _emailService = emailService;
        }

        [BindProperty]
        public RegisterViewModel RegisterViewModel { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Validating Email address (optional) due to options in Program.cs

            //Create user
            var user = new User
            {
                Email = RegisterViewModel.Email,
                UserName = RegisterViewModel.Email,
                Department = RegisterViewModel.Department,
                Position = RegisterViewModel.Position
            };

            var result = await this.userManager.CreateAsync(user, RegisterViewModel.Password);
            if (result.Succeeded)
            {
                var confirmationToken = await this.userManager.GenerateEmailConfirmationTokenAsync(user);
                var confirmationLink = Url.PageLink(pageName: "/Account/ConfirmEmail", values: new { userId = user.Id, token = confirmationToken });

                bool emailSuccess = await _emailService.SendConfirmationAsync(user.Email, "Please Confirm Your Email", $"Please click this link to confirm your email address: {confirmationLink}");

                if (emailSuccess)
                {
                    return RedirectToPage("/Account/Login");
                }
                else
                {
                    ModelState.AddModelError("Register", "Registration Error");
                    return Page();
                }
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("Register", error.Description);
                }

                return Page();
            }
        }

    }

    public class RegisterViewModel
    {
        [Required]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        public string Email { get; set; } = string.Empty;
        [Required]
        [DataType(dataType: DataType.Password)]
        public string Password { get; set; } = string.Empty;

        [Required]
        public string Department { get; set; }
        [Required]
        public string Position { get; set; }
    }
}

Web App/Pages/Account/AuthenticatorWithMFA.cshtml
@page
@model Web_App.Pages.Account.AuthenticatorWithMFAModel
@{
}

<h3>Please scan QR code or enter the key into your authenticator app</h3>

<p>
    @Model.MFAViewModel.Key
</p>

<p>
    <img src="@string.Format("data:image/png;base64,{0}",
        Convert.ToBase64String(Model.MFAViewModel.QrCodeBytes))" width="300" height="300" />
</p>

<br />
<form method="post">
    @if(Model.SetupSuccess)
    {
        <div class="alert alert-success">
            Authenticator Successfully Set Up
        </div>
    }
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="MFAViewModel.SecurityCode"></label>
        </div>
        <div class="col">
            <input type="text" asp-for="MFAViewModel.SecurityCode" class="form-control" autocomplete="off" />
        </div>
        <span class="text-danger" asp-validation-for="MFAViewModel.SecurityCode"></span>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Verify" />
        </div>
        <div class="col">
            <input type="hidden" asp-for="MFAViewModel.Key" />
            <input type="hidden" asp-for="MFAViewModel.QrCodeBytes" />
        </div>
    </div>
</form>

Web App/Pages/Account/ConfirmEmail.cshtml
@page
@model Web_App.Pages.Account.ConfirmEmailModel
@{
}

<p>
    @Model.Message
</p>

Web App/Pages/Account/Login.cshtml
@page
@model Web_App.Pages.Account.LoginModel
@{
}

<h3>Login</h3>
<br />
<div class="container border" style="padding: 20px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="CredentialViewModel.Email"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="CredentialViewModel.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="CredentialViewModel.Email"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="CredentialViewModel.Password"></label>
            </div>
            <div class="col-5">
                <input type="password" asp-for="CredentialViewModel.Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="CredentialViewModel.Password"></span>
        </div>
        <div class="row form-check mb-2">
            <div class="col-2">
                <input type="checkbox" asp-for="CredentialViewModel.RememberMe" class="form-check-input" />
                <label class="form-check-label" asp-for="CredentialViewModel.RememberMe"></label>
            </div>
            <div class="col-5">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Login" />
            </div>
            <div class="col-5">
                <a class="btn btn-link" href="/Account/Register">Sign Up</a>
            </div>
        </div>
        <br />
        <p>
            Social Media Logins:
            <div class="form-group">
                @foreach(var provider in Model.ExternalLoginProviders)
                {
                    <button type="submit" asp-page-handler="LoginExternally" name="provider" value="@provider.Name" class="btn btn-primary">
                        Login with @provider.Name
                    </button>
                }
            </div>
        </p>
    </form>
</div>

Web App/Pages/Account/LoginTwoFactor.cshtml
@page
@model Web_App.Pages.Account.LoginTwoFactorModel
@{
}

<p>
    <h3>Please enter the code from your email:</h3>
</p>
<div class="container border" style="padding 20px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="EmailMFA.SecurityCode"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="EmailMFA.SecurityCode" class="form-control" autocomplete="off" />
            </div>
            <span class="text-danger" asp-validation-for="EmailMFA.SecurityCode"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col">
                <input type="hidden" asp-for="EmailMFA.RememberMe" />
            </div>
        </div>
    </form>
</div>

Web App/Pages/Account/LoginTwoFactorAuthenticator.cshtml
@page
@model Web_App.Pages.Account.LoginTwoFactorAuthenticatorModel
@{
}

<p>
    <h3>Please enter the code from your authenticator:</h3>
</p>
<div class="container border" style="padding 20px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="AuthenticatorMFA.SecurityCode"></label>
            </div>
            <div class="col">
                <input type="text" asp-for="AuthenticatorMFA.SecurityCode" class="form-control" autocomplete="off" />
            </div>
            <span class="text-danger" asp-validation-for="AuthenticatorMFA.SecurityCode"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Verify" />
            </div>
            <div class="col">
                <input type="hidden" asp-for="AuthenticatorMFA.RememberMe" />
            </div>
        </div>
    </form>
</div>

Web App/Pages/Account/Logout.cshtml
@page
@model Web_App.Pages.Account.LogoutModel
@{
}

Web App/Pages/Account/Register.cshtml
@page
@model Web_App.Pages.Account.RegisterModel
@{
}

<h3>User Registration</h3>
<br />
<div class="container border" style="padding: 20px;">
    <form method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Email"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="RegisterViewModel.Email" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Email"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Password"></label>
            </div>
            <div class="col-5">
                <input type="password" asp-for="RegisterViewModel.Password" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Password"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Department"></label>
            </div>
            <div class="col-5">
                <input type="department" asp-for="RegisterViewModel.Department" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Department"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="RegisterViewModel.Position"></label>
            </div>
            <div class="col-5">
                <input type="position" asp-for="RegisterViewModel.Position" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="RegisterViewModel.Position"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Register" />
            </div>
            <div class="col-5">
            </div>
        </div>
    </form>
</div>

Web App/Pages/Account/UserProfile.cshtml
@page
@model Web_App.Pages.Account.UserProfileModel
@{
}

<form method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="UserProfile.Email"></label>
        </div>
        <div class="col-5">
            <input type="text" asp-for="UserProfile.Email" class="form-control" readonly />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Email"></span>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="UserProfile.Department"></label>
        </div>
        <div class="col-5">
            <input type="department" asp-for="UserProfile.Department" class="form-control" />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Department"></span>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="UserProfile.Position"></label>
        </div>
        <div class="col-5">
            <input type="position" asp-for="UserProfile.Position" class="form-control" />
        </div>
        <span class="text-danger" asp-validation-for="UserProfile.Position"></span>
    </div>
    <div class="form-group row">
        <div class="col-2">
            <input type="submit" class="btn btn-primary" value="Save" />
        </div>
        <div class="col-5">
        </div>
    </div>
</form>

@if (!string.IsNullOrWhiteSpace(Model.SuccessMessage)) 
{
    <div class="alert alert-success" role="alert">
        @Model.SuccessMessage
    </div>
}